"""Version-bound evidence; an old PASS must not certify new teaching code."""
import hashlib
from pathlib import Path
from .course import lessons

UI_NAMES = ('notebook_app.py','python_app.py','study_window.py','study_page.py','python_editor.py',
            'terminal_widget.py','feedback_panel.py','python_quiz_dialog.py',
            'python_teaching/practice_links.py','python_teaching/quiz_practice_links.json')


def fingerprint(ui=False):
    from engine import resource_path
    names=['notebook_teaching/'+n for n in (
        'course.py','engine.py','assets.py','guest_setup.py','guest_service.py','guest_lessons.py','assets-linux-x86_64.json')]
    if ui:names+=list(UI_NAMES)
    digest=hashlib.sha256()
    for name in names:
        path=resource_path(name)
        # In frozen builds normal modules live in the archive. Runtime proof
        # records the packaged source manifest, generated by the Linux build.
        if not path.is_file():
            import json
            manifest=json.loads(resource_path('notebook_teaching/source-hashes.json').read_text())
            sha=manifest[name]
        else:sha=hashlib.sha256(path.read_bytes()).hexdigest()
        digest.update(name.encode());digest.update(sha.encode())
    return digest.hexdigest()


def validate(report,ui=False):
    expected=({u['key']+':'+str(v) for u in lessons() for v in range(3)} if not ui else {
        'same_window_lazy_notebook','microstep_saved_without_completion','actual_vm_and_bash_ready',
        'shift_enter_executes_actual_selected_kernel','failed_grade_same_document_repair',
        'restart_keeps_code_not_namespace_or_old_output_pass','typed_bash_registration_refreshes_real_list',
        'hidden_notebook_vm_and_readers_close'})
    if report.get('state')!='complete' or set(report.get('passed',[]))!=expected or report.get('fingerprint')!=fingerprint(ui):
        raise RuntimeError('현재 Jupyter '+('UI' if ui else '전체 과정')+' 검증이 필요합니다.')
    if not ui and (report.get('vm_stopped') is not True or report.get('overlay_removed') is not True):
        raise RuntimeError('Jupyter 검증 환경 정리가 확인되지 않았습니다.')
    if not ui and not {'numpy_scalar_equivalent','package_removal_and_repair','direct_file_read_equivalent',
            'edited_and_old_kernel_outputs_not_saved','restart_in_wrong_environment_rejected',
            'repeat_mutation_with_trailing_output_rejected','order_in_both_environments_accepted',
            'target_kernel_recreation_equivalent'}.issubset(report.get('negative',[])):
        raise RuntimeError('Jupyter 오답·동등 풀이 검증이 필요합니다.')


def source_hashes():
    root=Path(__file__).resolve().parents[1]
    paths=[*Path(__file__).parent.glob('*.py'),Path(__file__).parent/'assets-linux-x86_64.json']
    paths += [root/n for n in UI_NAMES]
    return {p.relative_to(root).as_posix():hashlib.sha256(p.read_bytes()).hexdigest() for p in paths}
